functionsDirectory = "D:\\yaard-server-v50_prod\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "D:\\yaard-server-v50_prod\\public"
publishOrigin = "config"
functions = "D:\\yaard-server-v50_prod\\netlify\\functions"

  [build.environment]
  NODE_VERSION = "18"

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[functions]

  [functions.admin]
  timeout = 26

  [functions."*"]
  node_bundler = "esbuild"

[[headers]]
for = "/*"

  [headers.values]
  X-Frame-Options = "SAMEORIGIN"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/admin"
to = "/admin/"
status = 301
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/admin/"
to = "/admin/index.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/admin/*"
to = "/admin/index.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]